version: '3'

services:
  api:
    build: ./
    image: itswadesh/kitcommerce
    container_name: kitcommerce
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - HTTP_ENDPOINT=https://api.misiki.io
      - VITE_DOMAIN=kitcommerce.tech
      - NODE_ENV=production
      - PORT=3000

